import type { PortalRole } from "@/types";
import type { SessionResult } from "@/types";
import { ResultsDashboard } from "@/components/ResultsDashboard";
import { NotificationsPanel } from "@/components/NotificationsPanel";

interface RoleDashboardProps { role: PortalRole; results: SessionResult[]; userId: string; onPractice: () => void; onOfficial: () => void; }

const content: Record<PortalRole, { eyebrow: string; title: string; description: string; metrics: { label: string; value: string }[]; actions: string[] }> = {
  student: { eyebrow: "STUDENT DASHBOARD", title: "Build your next personal best.", description: "Your practice record, achievements, and competition activity will live here after sign-in.", metrics: [{ label: "Practice sessions", value: "Local" }, { label: "Competition status", value: "Coming soon" }, { label: "Certificates", value: "0" }], actions: ["Start practice", "Review answers", "View achievements"] },
  school: { eyebrow: "SCHOOL DASHBOARD", title: "Manage your spelling team.", description: "This foundation is ready for school profiles, student management, registrations, reports, and payment history.", metrics: [{ label: "Students", value: "—" }, { label: "Active competitions", value: "—" }, { label: "School ranking", value: "—" }], actions: ["Add students", "Register for a competition", "View school report"] },
  administrator: { eyebrow: "ADMINISTRATION", title: "Run a fair, connected competition.", description: "This foundation will host competition configuration, sentence libraries, rankings, reports, and system notices.", metrics: [{ label: "Registered schools", value: "—" }, { label: "Active events", value: "—" }, { label: "Pending reviews", value: "—" }], actions: ["Create competition", "Manage sentence library", "Publish announcement"] }
};

export function RoleDashboard({ role, results, userId, onPractice, onOfficial }: RoleDashboardProps) {
  const dashboard = content[role];
  const metrics = role === "student" ? [{ label: "Practice sessions", value: results.length.toString() }, { label: "Best accuracy", value: `${results.reduce((best, result) => Math.max(best, result.accuracy), 0)}%` }, { label: "Total XP", value: results.reduce((sum, result) => sum + result.xp, 0).toString() }] : dashboard.metrics;
  const actions = role === "student" ? [{ label: "Start practice", onClick: onPractice }, { label: "Enter official competition", onClick: onOfficial }] : role === "school" ? [{ label: "View school report", onClick: () => window.scrollTo({ top: 0, behavior: "smooth" }) }, { label: "View official rankings", onClick: onOfficial }] : [{ label: "Open competition console", onClick: onOfficial }, { label: "View administration report", onClick: () => window.scrollTo({ top: 0, behavior: "smooth" }) }];
  return <section className="animate-fade-in mx-auto w-full max-w-5xl pb-10"><div className="rounded-[2rem] bg-primary-600 p-7 text-white shadow-soft sm:p-10"><p className="text-sm font-black tracking-widest text-gold-400">{dashboard.eyebrow}</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">{dashboard.title}</h1><p className="mt-4 max-w-2xl text-lg text-white/80">{dashboard.description}</p></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl border border-primary-100 bg-white p-5 shadow-soft dark:border-slate-700 dark:bg-slate-800"><p className="text-3xl font-black text-primary-700 dark:text-gold-400">{metric.value}</p><p className="mt-1 text-sm font-bold text-slate-500">{metric.label}</p></div>)}</div><ResultsDashboard role={role} userId={userId} /><NotificationsPanel role={role} /><div className="mt-6 rounded-2xl border border-primary-100 bg-white p-6 shadow-soft dark:border-slate-700 dark:bg-slate-800"><h2 className="text-2xl font-black text-slate-950 dark:text-white">Workspace actions</h2><div className="mt-5 flex flex-wrap gap-3">{actions.map((action) => <button key={action.label} type="button" onClick={action.onClick} className="min-h-11 rounded-lg border border-primary-100 bg-primary-50 px-4 py-2 font-black text-primary-700 transition hover:bg-primary-100 dark:border-slate-600 dark:bg-slate-900 dark:text-gold-400">{action.label}</button>)}</div><p className="mt-5 text-sm text-slate-500 dark:text-slate-300">Student membership and school approval are managed in the administrator competition console.</p></div></section>;
}
